### ISSUE TITLE
not found on pypi

### ISSUE THREAD

**Issue by 0atman** [woodrush/py2hy#1]
How can I `pip install` this?

Thank you!

**Comment by koji-kojiro** [comment]
I think you need to clone this repo and install it by hand.

```bash
$ git clone https://github.com/woodrush/py2hy.git
$ cd ./py2hy
$ python setup.py install
```
But, `py2hy` seems to be broken...

```
$ py2hy test.py
Traceback (most recent call last):
  File "/usr/local/bin/py2hy", line 11, in <module>
    load_entry_point('py2hy==0.8.0', 'console_scripts', 'py2hy')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
```

**Comment by woodrush** [comment]
@0atman and @koji-kojiro , thanks for your comment! As @koji-kojiro said, currently py2hy is intended to be installed manually by `pip install -e .` .

However, the automatic compilation step in the installation process seems to be broken, making it impossible to install at the time. It could be worked around by rolling back a few commits, but I'll fix it soon to make it work.
